version: '2'
services:
    ilms2-app:
        image: ilms2
        external_links:
            - ilms2-mysql:mysql
            - ilms2-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ilms2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    ilms2-mysql:
        extends:
            file: mysql.yml
            service: ilms2-mysql
    ilms2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ilms2-elasticsearch
